### PR TITLE
update style guide to use linters

### PR DESCRIPTION
**Pull request by enochtsang**
This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/development-guide/14)

WIP need to update how to install AStyle for sublime and vim. As a note, we should install package control for sublime in the linux setup script.

### CODE REVIEW

**Comment by bill-luu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Style-Guide/README.adoc, line 34 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSmDTCxQ8mWf6i6celM:-KSmDTCyXidDHZtqDZL8:b9xrwls) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/5a3784181622df5e27b9012877d7d26f01d4ecaf/Style-Guide/README.adoc#L34)):*
> ```AsciiDoc
> ```bash
> astyle *.h *.cpp -r --dry-run --options=astylerc | grep Formatted
> ```
> ```

1) I got the following error when running: 
`Invalid option file options:
int 
Foo(bool
isBar)`
2) How is it supposed to work? Do I run the command while I'm in a directory and it goes through everything? Does the `astylerc` file need to be in the directory I'm in to run that command?

---

*[Style-Guide/README.adoc, line 79 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSmEQ41dIJw0lZJ8KT3:-KSmEQ42HG6JmXbpU1NI:bfaeaye) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/5a3784181622df5e27b9012877d7d26f01d4ecaf/Style-Guide/README.adoc#L79)):*
> ```AsciiDoc
> 
> Use gofmt. It's recommended to install an automatic gofmt in vim or sublime.
> ```

Adding a link for installation instructions here would be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14)*

**Comment by enochtsang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Style-Guide/README.adoc, line 34 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSmDTCxQ8mWf6i6celM:-KSmX9hs6FGO14ge0xHP:b-8a7u4n) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/5a3784181622df5e27b9012877d7d26f01d4ecaf/Style-Guide/README.adoc#L34)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> 1) I got the following error when running: 
> `Invalid option file options:
> int 
> Foo(bool
> isBar)`
> 2) How is it supposed to work? Do I run the command while I'm in a directory and it goes through everything? Does the `astylerc` file need to be in the directory I'm in to run that command?
</details>
Will clarify

---

*[Style-Guide/README.adoc, line 79 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSmEQ41dIJw0lZJ8KT3:-KSmXAtijESfZazVA7kA:b-gf59h1) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/5a3784181622df5e27b9012877d7d26f01d4ecaf/Style-Guide/README.adoc#L79)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Adding a link for installation instructions here would be good.
</details>
gofmt is built in when installing go, I'll make a note of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14)*

**Comment by bill-luu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Style-Guide/README.adoc, line 36 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSqOo-9kY-p0zexP1kQ:-KSqOo-9kY-p0zexP1kR:b275s6o) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/4f5b5f772de033d7c6563bc53bb5794567932db0/Style-Guide/README.adoc#L36)):*
> ```AsciiDoc
> To recursively format all `.cpp` and `.h` files:
> ```bash
> astyle *.cpp *.h -r
> ```

You need Quotation marks around `*.cpp` and `*.h`, or else you'll get a `Recursive option with no wildcard`error.

---

*[Style-Guide/README.adoc, line 48 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSqP9YelpB4jFDPDQ_-:-KSqP9YelpB4jFDPDQ_0:b-2tchro) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/4f5b5f772de033d7c6563bc53bb5794567932db0/Style-Guide/README.adoc#L48)):*
> ```AsciiDoc
> To check in a script whether are files are formatted correctly:
> ```bash
> astyle *.h *.cpp -r --dry-run --options=/path/to/astylerc | grep Formatted
> ```

Same as above, quotations around `*.cpp` and `*.h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14)*

**Comment by enochtsang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Style-Guide/README.adoc, line 36 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSqOo-9kY-p0zexP1kQ:-KSqg61qvkfF5iBHQPZ8:b-oz6p4p) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/4f5b5f772de033d7c6563bc53bb5794567932db0/Style-Guide/README.adoc#L36)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> You need Quotation marks around `*.cpp` and `*.h`, or else you'll get a `Recursive option with no wildcard`error.
</details>
I'm using these same commands in a different project though. Interesting, doesn't hurt to put them in, I'll add them.

---

*[Style-Guide/README.adoc, line 48 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-KSqP9YelpB4jFDPDQ_-:-KSqgF-MFQCkpOt2ZKDR:b-oz6p4p) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/4f5b5f772de033d7c6563bc53bb5794567932db0/Style-Guide/README.adoc#L48)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Same as above, quotations around `*.cpp` and `*.h`.
</details>
I'm using these same commands in a different project though. Interesting, doesn't hurt to put them in, I'll add them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14)*

**Comment by bill-luu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/14#-:-KTI60WQV2KsRauzKQRY:bnfp4nl)*

**Pull request merged**
