### PR TITLE
Created guide for formatting to astyle in neovim

### PR DESCRIPTION
**Pull request by Ben-Graham**
created guide for installing and using astyle formatting commands in vim, and setting up an auto command to format into astyle when quitting out of vim.

---
This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/development-guide/16)

### CODE REVIEW

**Comment by enochtsang** [comment]
The commit name is bad, it should be what you've done in that commit. Initial commit would be for initiating a repository.

**Comment by enochtsang** [comment]
Thanks for getting this in, you should fix your commit message though, it should be what you've done in that commit. "Initial commit" would be for initiating a repository.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16#-KT6CQuo7eusNTwv-_Vw:-KT6CQuo7eusNTwv-_Vx:b-irhbpp) (no related file):*
Your astyle formatting is weird. Here's a [syntax reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/). 

Titles should be using equal signs
```
= Title
== Header 2
=== Header 3
```

There's no need for big `-------------` or `~~~~~~~~~~` separators. 

Code blocks should have a `----` above and below them.

````
[source,c++]
----
cout << "Hello world!" << endl;
----
````

---

*[Vim-Astyle-Guide/README.adoc, line 2 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16#-KT6CbuPnSw3UtWuJqdr:-KT6CbuPnSw3UtWuJqds:b-m98638) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/01743c37a5ae2a176ddad32b9d5039a59e76da3a/Vim-Astyle-Guide/README.adoc#L2)):*
> ```AsciiDoc
> Formatting to Astyle in Vim
> ---------------------------
> ```

New line per sentence is standard in asciidoc.

---

*[Vim-Astyle-Guide/README.adoc, line 19 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16#-KT6CXpMx5Wrj0pZE7K-:-KT6CXpMx5Wrj0pZE7K0:b-vw4sa6) ([raw file](https://github.com/ucsolarcarteam/development-guide/blob/01743c37a5ae2a176ddad32b9d5039a59e76da3a/Vim-Astyle-Guide/README.adoc#L19)):*
> ```AsciiDoc
> Running astyle as an autocommand
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> To run the astyle command everytime you save and quit vim, add the following code to the general section of your init.vim file.
> ```

I think nvim and vim will handle this differently right? Also if not, where is the init.vim file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16#-:-KT6CJkLSDufWdCu8xVn:bqqods9)*

**Comment by Ben-Graham** [comment]
I haven't read anything saying that vim and neovim will handle this differently, but I am not 100% certain so to be safe I will edit it to more specifically apply to neovim.

**Comment by enochtsang** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16#-KTw1HC89km0mEEZykNE:-KTw1HC89km0mEEZykNF:b-y285gr) (no related file):*
This command needs to able to linked to the astylerc somehow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/development-guide/16)*

**Comment by bseto** [comment]
Instructions are clear. 
The autocmd works well and works for cpp and .h files only so that's good.
Merging!

**Comment by enochtsang** [comment]
Byron, this doesn't link to the astylerc does it? That's a problem, someone following this blindly will just keep running astyle on a file but with the wrong configuration.

**Pull request merged**
